
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.matus.analyzers;

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int string = 22;
  public static final int asterisk = 15;
  public static final int number = 21;
  public static final int key_c = 7;
  public static final int semicolon = 10;
  public static final int or_sign = 16;
  public static final int range = 5;
  public static final int EOF = 0;
  public static final int morethan = 9;
  public static final int id = 19;
  public static final int dot = 14;
  public static final int section_separator = 13;
  public static final int error = 1;
  public static final int score = 8;
  public static final int word = 20;
  public static final int colon = 11;
  public static final int s_simplequote = 3;
  public static final int s_newline = 2;
  public static final int range_special_char = 18;
  public static final int plus_sign = 17;
  public static final int String = 23;
  public static final int s_doublequote = 4;
  public static final int comma = 12;
  public static final int key_o = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "s_newline",
  "s_simplequote",
  "s_doublequote",
  "range",
  "key_o",
  "key_c",
  "score",
  "morethan",
  "semicolon",
  "colon",
  "comma",
  "section_separator",
  "dot",
  "asterisk",
  "or_sign",
  "plus_sign",
  "range_special_char",
  "id",
  "word",
  "number",
  "string",
  "String"
  };
}

