
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.matus.analyzers;

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int string = 23;
  public static final int asterisk = 17;
  public static final int comment = 2;
  public static final int number = 22;
  public static final int multicomment = 3;
  public static final int key_c = 9;
  public static final int or_sign = 18;
  public static final int semicolon = 12;
  public static final int range = 7;
  public static final int EOF = 0;
  public static final int morethan = 11;
  public static final int id = 20;
  public static final int dot = 16;
  public static final int section_separator = 15;
  public static final int error = 1;
  public static final int score = 10;
  public static final int word = 21;
  public static final int colon = 13;
  public static final int s_simplequote = 5;
  public static final int s_newline = 4;
  public static final int range_special_char = 19;
  public static final int s_doublequote = 6;
  public static final int comma = 14;
  public static final int key_o = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "comment",
  "multicomment",
  "s_newline",
  "s_simplequote",
  "s_doublequote",
  "range",
  "key_o",
  "key_c",
  "score",
  "morethan",
  "semicolon",
  "colon",
  "comma",
  "section_separator",
  "dot",
  "asterisk",
  "or_sign",
  "range_special_char",
  "id",
  "word",
  "number",
  "string"
  };
}

